version: '3.8'

services:
  supabase-auth:
    image: supabase/gotrue:v2.99.0
    depends_on:
      supabase-db:
        condition: service_healthy
    networks:
      - aider-network
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL:-http://localhost:8000}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@supabase-db:5432/postgres?search_path=auth
      GOTRUE_SITE_URL: ${SITE_URL:-http://localhost:8443}
      GOTRUE_JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      GOTRUE_JWT_EXP: 3600

  supabase-rest:
    image: postgrest/postgrest:v11.2.0
    depends_on:
      supabase-db:
        condition: service_healthy
    networks:
      - aider-network
    environment:
      PGRST_DB_URI: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@supabase-db:5432/postgres
      PGRST_DB_SCHEMAS: public,storage
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}

  supabase-realtime:
    image: supabase/realtime:v2.10.1
    depends_on:
      supabase-db:
        condition: service_healthy
    networks:
      - aider-network
    environment:
      DB_HOST: supabase-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: postgres
      API_JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}

  supabase-storage:
    image: supabase/storage-api:v0.40.4
    depends_on:
      supabase-db:
        condition: service_healthy
    networks:
      - aider-network
    volumes:
      - supabase-storage:/var/lib/storage
    environment:
      ANON_KEY: ${SUPABASE_ANON_KEY}
      SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      POSTGREST_URL: http://supabase-rest:3000
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@supabase-db:5432/postgres

volumes:
  supabase-storage:

networks:
  aider-network:
    driver: bridge