# Use the official Jekyll image from Docker Hub
FROM bretfisher/jekyll-serve

WORKDIR /site

# Copy website files and install dependencies in one layer
COPY aider/website /site

RUN apt-get update && \
    apt-get install -y libcurl4 && \
    rm -rf /var/lib/apt/lists/* && \
    bundle install --retry 5 --jobs 20

ENTRYPOINT [ "docker-entrypoint.sh" ]

CMD [ "bundle", "exec", "jekyll", "serve", "--verbose", "--trace", "--force_polling", "-H", "0.0.0.0", "-P", "4000" ]
